---
version: 0.0.0
global:
  tech: websphere
  language: java
  jkd: 8
qa:
  route1:
    build:
      sonarQubeScan:
        projectKey: Valaxy
        projectName: ValaxyDemo
        projectVersion: 1.0
  qa:
  route2:
