---
global:
  tech: websphere
  language: java
  jkd: 8
production:
  route1:
    build:
      sonarQubeScan:
        sources: C:\Users\Indra\.jenkins\workspace\DEMO_PROYECTOS\route-1\src
        projectKey: SimpleCustomerApp
        projectName: SCA
