---
global:
  tech: websphere
  language: java
  jkd: 8
qa:
  route1:
    build:
      sonarQubeScan:
        sources: SimpleCustomerApp/build/
        projectKey: SimpleCustomerApp
        projectName: SCA
